src/config/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import include, path
from students.views import index


urlpatterns = [
    path("", index, name='index'),
    path("core/", include("core.urls")),
    path("admin/", admin.site.urls),
    path("students/", include("students.urls")),
    path("teachers/", include("teachers.urls")),
    path("groups/", include("group.urls")),
    path("__debug__/", include(debug_toolbar.urls)),
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#

src/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("polls/", views.index, name="polls"),
]

src/group/urls.py
from django.urls import path
from group.views import get_all_groups, create_group, update_group, delete_group

app_name = "group"

urlpatterns = [
    path("", get_all_groups, name="all_groups"),
    path("create_group/", create_group, name="create_group"),
    path("update/<int:pk>/", update_group, name="update_group"),
    path("delete/<int:pk>/", delete_group, name="delete_group"),
]

src/students/urls.py
from django.urls import path

from students.views import get_all_students, create_student, update_student, delete_student

app_name = "students"

urlpatterns = [
    # path('', index, name='index'),
    path("", get_all_students, name="all_students"),
    path("create/", create_student, name="create_student"),
    path("update/<uuid:pk>/", update_student, name="update_student"),
    path("delete/<uuid:pk>/", delete_student, name="delete_student"),

]

src/teachers/urls.py
from django.urls import path
from teachers.views import get_all_teachers, create_teacher, update_teacher, delete_teacher

app_name = "teachers"

urlpatterns = [
    path("all_teachers", get_all_teachers, name="all_teachers"),
    path("create/", create_teacher, name="create_teacher"),
    path("update/<int:pk>/", update_teacher, name="update_teacher"),
    path("delete/<int:pk>/", delete_teacher, name="delete_teacher"),
]

src/templates/groups_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/groups_edit.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/groups_list.html
{% extends "index.html" %}

{% block content %}

    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#id</th>
            <th scope="col">Name</th>
            <th scope="col">Date of creation</th>
            <th scope="col">Rating</th>
            <th scope="col">Active:</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for g in group %}
            <tr>
                <th scope="row">{{ g.pk }}</th>
                <td>{{ g.name }}</td>
                <td>{{ g.date_of_creation }}</td>
                <td>{{ g.rating }}</td>
                <td>{{ g.is_active }}</td>
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'group:update_group' g.pk %}">Edit</a>
                </td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url 'group:delete_group' g.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/index.html
{%  load static  %}
<!doctype html>
<html lang="en" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author"
          content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.101.0">
    <title>Cover Template · Bootstrap v5.2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
    <link rel="canonical"
          href="https://getbootstrap.com/docs/5.2/examples/cover/">


    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .nav-link {
            margin-right: 4px;
            margin-left: 2px;
        }
    </style>



    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
</head>
<body class="d-flex h-100 text-center text-bg-dark">

<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">LMS</h3>
            <nav class="nav nav-masthead justify-content-center float-md">
                <a class="nav-link fw-bold py-1 px-0 active"
                   aria-current="page"
                   href="{% url 'index' %}">Home</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:all_students' %}">Students list</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'teachers:all_teachers' %}">Teachers list</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'group:all_groups' %}">Groups list</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'students:create_student' %}">Create Student</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'teachers:create_teacher' %}">Create Teacher</a>

                <a class="nav-link fw-bold py-1 px-0"
                   href="{% url 'group:create_group' %}">Create Group</a>
            </nav>
        </div>
    </header>



    <main class="px-3">

        {% block content %}

            <h1>LMS</h1>

            <img src="{% static 'img/online_learning.png' %}" alt="" width="350" class="bd-placeholder-img">


            <p class="lead">LMS is an online platform, which helps teachers and students create learning groups.</p>
            <p class="lead">

                <a type="button" class="btn btn-primary" href="{% url 'students:all_students' %}">To the students</a>

            </p>
        {% endblock %}
    </main>

    <footer class="mt-auto text-white-50">
        <p>Cover template for <a href="https://getbootstrap.com/"
                                 class="text-white">Bootstrap</a>, by <a
                href="https://twitter.com/mdo" class="text-white">@mdo</a>.</p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
</body>
</html>

src/templates/students_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/students_edit.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/students_list.html
{% extends "index.html" %}
{% load static %}
{% block content %}

    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Age</th>
            <th scope="col">Grade</th>
            <th scope="col">Group</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
            <th scope="col">CV</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for student in students %}
            {% if student.avatar %}
            <td><img src="{% static student.avatar.url %}" alt="" height="100" width="100" class="mr-3"></td>
            {% else %}
            <td>No photo</td>
            {% endif %}
            <td>{{ student.first_name }}</td>
            <td>{{ student.last_name }}</td>
            <td>{{ student.email }}</td>
            {% if student.birth_date %}
                <td>{{ student.birth_date }}</td>
                <td>{{ student.age }}</td>
            {% else %}
                <td>Undefined</td>
                <td>Undefined</td>
            {% endif %}
            <td>{{ student.grade }}</td>
            <td>{{ student.group }}</td>
            <td><a type="button" class="btn btn-warning" href="{% url 'students:update_student' student.pk %}">Edit</a>
                </td>
            <td><a type="button" class="btn btn-danger"
                       href="{% url 'students:delete_student' student.pk %}">Delete</a>
                </td>
            {% if student.cv %}
                <td><a type="button" class="btn btn-success"
                       href="{% static student.cv.url %}">CV</a>
                </td>
                {% else %}
                <td>No CV</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}

src/templates/teachers_create.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Create">Create
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/teachers_edit.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% csrf_token %}
{% block content %}
    <div>
        <form method="POST" style="width: 25em;
         align-content: center
         ; margin: auto;">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary" value="Update">Update
            </button>
        </form>
    </div>
{% endblock content %}

src/templates/teachers_list.html
{% extends "index.html" %}

{% load static %}

{% block content %}

    <table class="table table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Birth date</th>
            <th scope="col">Group</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
        </tr>
        </thead>
        <tbody class="table-group-divider">
        {% for teacher in teachers %}
            <tr>
                <td><img src="{% static teacher.avatar.url %}" alt="" height="100" width="100" class="mr-3"></td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.birth_date }}</td>
                    {% for g in teacher.group.all %}
                        <td><a href="{% url 'group:update_group' g.pk %}">{{ g.name }}</a></td>
                        {% endfor %}
                <td><a type="button" class="btn btn-warning"
                       href="{% url 'teachers:update_teacher' teacher.pk %}">Edit</a>
                </td>
                <td><a type="button" class="btn btn-danger"
                       href="{% url 'teachers:delete_teacher' teacher.pk %}">Delete</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock content %}